/**
 * sd.build.mjs — Style Dictionary v5 build
 *
 * Sources:  primitives → semantics → components (order matters for reference resolution)
 * Outputs:
 *   output/css/variables.css       — CSS custom properties (:root)
 *   output/css/tailwind-v4.css     — @theme block for Tailwind v4
 *   output/js/tokens.mjs           — ES module with typed token constants
 */

import fs from 'node:fs';
import StyleDictionary from 'style-dictionary';
import { fileHeader, formattedVariables } from 'style-dictionary/utils';

// ─── Custom format: Tailwind v4 @theme block ─────────────────────────────────
StyleDictionary.registerFormat({
  name: 'css/tailwind-v4',
  format: async ({ dictionary, options, file }) => {
    const header = await fileHeader({ file });
    const vars = formattedVariables({
      format: 'css',
      dictionary,
      outputReferences: options.outputReferences ?? false,
      usesDtcg: true,
    });
    return `${header}@theme {\n${vars}}\n`;
  },
});

// ─── Custom format: ES module token constants ─────────────────────────────────
StyleDictionary.registerFormat({
  name: 'javascript/es-module',
  format: async ({ dictionary, file }) => {
    const header = await fileHeader({ file });
    const lines = dictionary.allTokens.map(token => {
      const key = token.name
        .replace(/-([a-z])/g, (_, c) => c.toUpperCase())   // camelCase
        .replace(/^(.)/, c => c.toLowerCase());
      return `export const ${key} = ${JSON.stringify(token.$value ?? token.value)};`;
    });
    return `${header}${lines.join('\n')}\n`;
  },
});

// ─── Config ───────────────────────────────────────────────────────────────────
const sd = new StyleDictionary({
  log: { verbosity: 'default' },
  usesDtcg: true,

  source: [
    'primitives.tokens.json',
    'semantics.tokens.json',
    'components.tokens.json',
  ],

  platforms: {
    // 1. CSS custom properties — resolved final values, works everywhere
    css: {
      transformGroup: 'css',
      buildPath: 'output/css/',
      files: [
        {
          destination: 'variables.css',
          format: 'css/variables',
          options: {
            outputReferences: false,   // fully resolved hex/px values
            selector: ':root',
          },
        },
      ],
    },

    // 2. Tailwind v4 @theme block — same values, different wrapper
    tailwindV4: {
      transformGroup: 'css',
      buildPath: 'output/css/',
      files: [
        {
          destination: 'tailwind-v4.css',
          format: 'css/tailwind-v4',
          options: { outputReferences: false },
        },
      ],
    },

    // 3. ES module constants — for TypeScript / JS consumers
    js: {
      transformGroup: 'js',
      buildPath: 'output/js/',
      files: [
        {
          destination: 'tokens.mjs',
          format: 'javascript/es-module',
        },
      ],
    },
  },
});

await sd.buildAllPlatforms();

// ─── Write the app stylesheet ────────────────────────────────────────────────
// enpath-ui/src/app/tokens.css is GENERATED from output/css/variables.css — never
// edit it by hand. The only difference: component tokens that alias a semantic
// token keep a live var() reference instead of the resolved hex, so they follow
// the semantic token without a rebuild.
const LIVE_ALIASES = {
  '--tooltip-bg': 'var(--color-background-inverted)',
  '--tooltip-fg': 'var(--color-background-inverted-foreground)',
};
const vars = fs.readFileSync(new URL('./output/css/variables.css', import.meta.url), 'utf8');
const body = vars.split('\n').map((line) => {
  const m = line.match(/^(\s*)(--[\w-]+):\s*[^;]+;(.*)$/);
  return m && LIVE_ALIASES[m[2]] ? `${m[1]}${m[2]}: ${LIVE_ALIASES[m[2]]};${m[3]}` : line;
}).join('\n');
const header = '/**\n * GENERATED by Tokens/sd.build.mjs from Tokens/*.tokens.json — do not edit.\n * Light mode only.\n */\n';
fs.writeFileSync(new URL('../enpath-ui/src/app/tokens.css', import.meta.url), header + body.replace(/^\/\*\*[\s\S]*?\*\/\n/, ''));
// ─── Write the text styles ───────────────────────────────────────────────────
// enpath-ui/src/app/text-styles.css is GENERATED from semantics typography/* — one
// Tailwind class per style (text-body-sm, text-label-md …) carrying size, line height
// and weight. A line height that references a px pair (line-height/text-*) is divided
// by the size; one that references a ratio (none, snug …) is stored ×100, so ÷ 100.
const semantics = JSON.parse(fs.readFileSync(new URL('./semantics.tokens.json', import.meta.url), 'utf8'));
const styleLines = Object.entries(semantics.typography ?? {}).flatMap(([name, t]) => {
  const v = (prop) => `var(--typography-${name}-${prop})`;
  const lh = t['line-height'].$value.startsWith('{line-height.text-')
    ? `calc(${v('line-height')} / ${v('font-size')})`
    : `calc(${v('line-height')} / 100)`;
  return [
    `  --text-${name}: calc(${v('font-size')} / 16 * 1rem);`,
    `  --text-${name}--line-height: ${lh};`,
    `  --text-${name}--font-weight: ${v('font-weight')};`,
  ];
});
fs.writeFileSync(
  new URL('../enpath-ui/src/app/text-styles.css', import.meta.url),
  '/**\n * GENERATED by Tokens/sd.build.mjs from Tokens/semantics.tokens.json typography/* — do not edit.\n' +
  ' * Each style is one class: text-{name} = size + line height + weight.\n */\n\n' +
  `@theme inline {\n${styleLines.join('\n')}\n}\n`,
);
console.log('\n✓ Build complete → output/css/ · output/js/ · enpath-ui/src/app/tokens.css · text-styles.css');
