import type { Metadata } from "next"

import { CatalogView } from "./catalog-view"

/* Everything the product has, in one place, each with an ID to hand an agent.
   The data is catalog.json, generated by build-catalog.mjs; rerun it after
   adding or renaming a component, story, pattern or template. */

export const metadata: Metadata = {
  title: "Catalog · Product", // ADAPT: product name
}

export default function CatalogPage() {
  return <CatalogView />
}
